[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    dir = "public"

[[plugins]]
package = "@netlify/plugin-gatsby"

  [plugins.inputs]
    buildCommand = "gatsby build"
    gatsbyDirectory = "."
