[[plugins]]
name = "netlify-plugin-sitemap"
package = "netlify-plugin-sitemap"
inputs = [
  "buildDir = public"
]


[[plugins]]
name = "@netlify/plugin-gatsby"
package = "@netlify/plugin-gatsby"
inputs = [
  "buildCommand = gatsby build",
  "gatsbyDirectory = ."
]