[[plugins]]
package = "netlify-plugin-sitemap"
inputs = [
  "buildDir = public"
]


[[plugins]]
package = "@netlify/plugin-gatsby"
inputs = [
  "buildCommand = gatsby build",
  "gatsbyDirectory = ."
]